receivers:
  cgoreceiver:
    subscribe:
      - name: syscall_exit-writev
        category: net
      - name: syscall_exit-readv
        category: net
      - name: syscall_exit-write
        category: net
      - name: syscall_exit-read
        category: net
      - name: syscall_exit-sendto
        category: net
      - name: syscall_exit-recvfrom
        category: net
      - name: syscall_exit-sendmsg
        category: net
      - name: syscall_exit-recvmsg
        category: net
      - name: kprobe-tcp_close
      - name: kprobe-tcp_rcv_established
      - name: kprobe-tcp_drop
      - name: kprobe-tcp_retransmit_skb
      - name: syscall_exit-connect
      - name: kretprobe-tcp_connect
      - name: kprobe-tcp_set_state
analyzers:
  mockanalyzer:
    num: 10
  networkanalyzer:
    connect_timeout: 100
    request_timeout: 1
    response_slow_threshold: 500
    enable_conntrack: true
    conntrack_max_state_size: 131072
    conntrack_rate_limit: 500
    proc_root: /proc
    protocol_parser: [ http, mysql, dns, redis, kafka, dubbo ]
    protocol_config:
      - key: "http"
        payload_length: 200
      - key: "dubbo"
        payload_length: 200
      - key: "mysql"
        slow_threshold: 100
        disable_discern: false
      - key: "kafka"
        slow_threshold: 100
      - key: "cassandra"
        ports: [ 9042 ]
        slow_threshold: 100
      - key: "s3"
        ports: [ 9190 ]
        slow_threshold: 100
      - key: "dns"
        ports: [ 53 ]
        slow_threshold: 100

processors:
  k8smetadataprocessor:
    kube_auth_type: kubeConfig
  nodemetricprocessor:

exporters:
  otelexporter:
    metric_aggregation_map:
      kindling_entity_request_total: counter
      kindling_entity_request_duration_nanoseconds_total: counter
      kindling_entity_request_average_duration_nanoseconds: histogram
      kindling_entity_request_send_bytes_total: counter
      kindling_entity_request_receive_bytes_total: counter
      kindling_topology_request_total: counter
      kindling_topology_request_duration_nanoseconds_total: counter
      kindling_topology_request_average_duration_nanoseconds: histogram
      kindling_topology_request_request_bytes_total: counter
      kindling_topology_request_response_bytes_total: counter
      kindling_trace_request_duration_nanoseconds: gauge
      kindling_tcp_srtt_microseconds: gauge
      kindling_tcp_retransmit_total: counter
      kindling_tcp_packet_loss_total: counter
    export_kind: prometheus
    custom_labels:
      job: test-hcmine
    prometheus:
      port: :8080
    otlp:
      collect_period: 15s
      endpoint: 10.10.10.10:8080
    stdout:
      collect_period: 15s

observability:
  logger:
    console_level: debug # debug,info,warn,error,none
    file_level: debug
    file_rotation:
      filename: agent.log
      maxsize: 512 #MB
      maxage: 30 #day
      maxbackups: 5
      localtime: true
      compress: false
  opentelemetry:
    # Export data in the following ways: ["prometheus", "otlp", "stdout"]
    # Note: configure the corresponding section to make everything ok
    export_kind: stdout
    prometheus:
      port: :9501
    otlp:
      collect_period: 15s
      # Note: DO NOT add the prefix "http://"
      endpoint: 10.10.10.10:8080
    stdout:
      collect_period: 15s